Repository Dev-FE-1/Toy_Project_3_Team5, pull requests merged in 2024-09, with the labels that each got.

#91 [fix] popular 스타일링 수정 작업
  src/pages/common/Popular.tsx
Labels: 🛠️ Fix

#93 [fix] InputBox 컴포넌트 수정
  src/components/InputBox.tsx
Labels: 🛠️ Fix

#98 [fix] 플레이리스트 카드 컴포넌트 퍼블리싱 수정
  src/components/Layout.tsx
  src/components/Modal.tsx
  src/components/PlaylistCard.tsx
  src/types/playlistType.ts
Labels: 🛠️ Fix

#102 [feature] Header 컴포넌트 검색 키워드 기반 라우팅 구현
  package-lock.json
  package.json
  src/components/Header.tsx
Labels: ✨ Feature

#103 [refactor] 접속 페이지별 헤더 타입 변경 기능 추가
  src/components/Header.tsx
  src/components/Layout.tsx
  src/router/router.tsx
  src/types/header.ts
  src/utils/headerUtils.ts
Labels: 🪛 Refactor, ✨ Feature

#110 [feature] 회원가입 UI 퍼블리싱 & 기능 구현
  src/components/InputBox.tsx
  src/firebase/firbaseConfig.ts
  src/pages/common/SignIn.tsx
  src/pages/common/SignUp.tsx
  src/stores/useAuthStore.ts
Labels: 🎨 Design, ✨ Feature

#114 [fix] useAuthStore 전역 상태 관리 데이터 수정
  src/stores/useAuthStore.ts
Labels: 🛠️ Fix

#111 [feature] 플레이리스트 생성 페이지 개발
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/playlist.ts
  src/api/video.ts
  src/assets/logoIcon.png
  src/assets/logoTitle.png
  src/components/InputBox.tsx
  src/components/Layout.tsx
  src/components/PlaylistCard.tsx
  src/components/Toast.tsx
  src/components/Toggle.tsx
  src/components/Video.tsx
  src/components/playlist/AddedVideo.tsx
  src/firebase/firbaseConfig.ts
  src/hooks/useToast.ts
  src/pages/playlist/PlayListAdd.tsx
  src/router/router.tsx
  src/stores/useToastStore.ts
  src/types/api.ts
  src/types/playlistType.ts
  src/types/route.ts
  src/types/video.ts
  src/utils/textUtils.ts
  src/utils/videoUtils.ts
Labels: 📬 API, 🪛 Refactor, ✨ Feature

#117 [fix] 인기 페이지 api의 타입값에 맞게 조정
  src/hooks/useTagFetch.ts
  src/pages/common/Popular.tsx
  src/types/playlistType.ts
Labels: 🛠️ Fix

#122 [feature] 플레이리스트 생성페이지 validation 기능 추가
  src/api/video.ts
  src/components/Toast.tsx
  src/constants/validation.ts
  src/hooks/useToast.ts
  src/pages/playlist/PlayListAdd.tsx
  src/stores/useToastStore.ts
  src/utils/textUtils.ts
  src/utils/videoUtils.ts
Labels: 🪛 Refactor, ✨ Feature

#125 [feature] 마이플리 페이지 필터링 구현
  src/api/myplaylists.ts
  src/hooks/usePlaylist.ts
  src/pages/playlist/PlayListHome.tsx
  src/pages/playlist/PlayListLikes.tsx
  src/pages/playlist/PlayListSaved.tsx
  src/utils/filterUtils.ts
Labels: ✨ Feature

#126 [feature] 검색 결과 페이지 구현
  src/api/searchPlaylist.ts
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/constants/route.ts
  src/pages/common/Search.tsx
  src/router/router.tsx
Labels: ✨ Feature

#124 [feature] 팔로잉 페이지 기능구현
  src/hooks/useChannelFetch.ts
  src/hooks/useFollowingPlaylistFetch.ts
  src/mock/popularPlaylist-test.ts
  src/pages/common/Following.tsx
Labels: ✨ Feature

#134 [feature] 플레이리스트 관리 api 개발
  src/api/playlistInfo.ts
Labels: 📬 API

#131 [feature] 마이플리 페이지 개발
  src/api/chennelInfo.ts
  src/components/Navbar.tsx
  src/hooks/useFollowToggle.ts
  src/pages/playlist/PlayList.tsx
  src/pages/playlist/PlayListHome.tsx
  src/pages/playlist/PlayListLikes.tsx
  src/pages/playlist/PlayListSaved.tsx
Labels: ✨ Feature

#136 [feature] 팔로잉 페이지 무한 스크롤 기능 구현
  src/api/followingPlaylists.ts
  src/hooks/useChannelFetch.ts
  src/hooks/useFollowingPlaylistFetch.ts
  src/pages/common/Following.tsx
Labels: ✨ Feature

#139 [feature] 플레이리스트 카드 관련 기능 구현
  src/api/myplaylists.ts
  src/api/playlistActions.ts
  src/components/Modal.tsx
  src/components/PlaylistCard.tsx
  src/hooks/usePlaylistActions.ts
  src/pages/playlist/PlayListHome.tsx
  src/stores/useAuthStore.ts
  src/stores/useVisibilityStore.ts
Labels: 📬 API, ✨ Feature

#142 [test] 로그인 페이지 테스트 코드 작성
  .gitignore
  playwright.config.js
  src/tests/signIn.spec.js
Labels: ☑️ Test

#144 [fix] 플레이리스트 좋아요 기능 및 개수 동기화 로직 수정
  src/hooks/usePlaylistActions.ts
Labels: 🛠️ Fix

#145 [feature] 프로필 수정 페이지 UI 퍼블리싱 & 기능구현
  src/api/profileInfo.ts
  src/components/HashTag.tsx
  src/components/Header.tsx
  src/hooks/useCheckDuplicate.ts
  src/hooks/useHashtagManage.ts
  src/pages/common/SignUp.tsx
  src/pages/profile/ProfileUpdate.tsx
  src/utils/checkDuplicate.ts
Labels: 🎨 Design, ✨ Feature

#146 [feature] 상세페이지 개발
  src/api/comment.ts
  src/api/playlistInfo.ts
  src/api/profileInfo.ts
  src/api/video.ts
  src/assets/vimeo.png
  src/assets/youtube.png
  src/components/Comment.tsx
  src/components/MiniPlaylist.tsx
  src/components/Profile.tsx
  src/components/Video.tsx
  src/components/playlist/AddedVideo.tsx
  src/constants/playlist.ts
  src/constants/validation.ts
  src/hooks/useDetailForm.ts
  src/hooks/usePlaylistInfo.ts
  src/mock/comment-data.json
  src/mock/playlist-data.json
  src/mock/user-data.json
  src/pages/common/Detail.tsx
  src/pages/playlist/PlayListAdd.tsx
  src/pages/playlist/PlayListEdit.tsx
  src/router/router.tsx
  src/types/api.ts
  src/types/playlistType.ts
  src/utils/profileUtils.ts
  src/utils/textUtils.ts
  src/utils/videoUtils.ts
Labels: 🪛 Refactor, ✨ Feature

#151 [feature] 검색 결과 페이지 태그 검색 기능 추가 구현
  src/api/searchPlaylists.ts
Labels: 📬 API, ✨ Feature

#153 [design] 최종 스타일 통합
  src/components/Comment.tsx
  src/components/MiniPlaylist.tsx
  src/components/Navbar.tsx
  src/components/PlaylistCard.tsx
  src/components/Video.tsx
  src/components/playlist/AddedVideo.tsx
  src/pages/common/Detail.tsx
  src/pages/common/Following.tsx
  src/pages/common/Popular.tsx
  src/pages/common/SignUp.tsx
  src/pages/profile/ProfileFollower.tsx
  src/pages/profile/ProfileFollowing.tsx
  src/pages/profile/ProfileUpdate.tsx
Labels: 🎨 Design

#155 [bug] 마이플리 페이지 버그픽스
  src/components/PlaylistCard.tsx
  src/pages/playlist/PlayListAdd.tsx
  src/pages/playlist/PlayListHome.tsx
Labels: 🐛 Bug, 🛠️ Fix

#159 [bug] 구글 로그인 버그픽스
  src/pages/common/SignIn.tsx
Labels: 🐛 Bug, 🛠️ Fix

#160 [ bug] 팔로잉 uid로 들어가는 문제 해결
  src/api/chennelInfo.ts
  src/hooks/useFollowToggle.ts
  src/pages/profile/ProfileFollower.tsx
  src/pages/profile/ProfileFollowing.tsx
Labels: 🐛 Bug

#163 [bug] useFollowToggle 훅 수정
  src/hooks/useFollowToggle.ts
Labels: 🐛 Bug

#164 [bug] 프로필 수정 채널이름 중복 검사 문제 해결
  src/pages/profile/ProfileUpdate.tsx
Labels: 🐛 Bug, 🛠️ Fix

#165 [bug] 담당한 버그 픽스
  src/api/comment.ts
  src/api/profileInfo.ts
  src/components/Comment.tsx
  src/components/PlaylistCard.tsx
  src/hooks/useDetailForm.ts
  src/hooks/usePlaylistActions.ts
  src/hooks/usePlaylistInfo.ts
  src/pages/common/Detail.tsx
  src/pages/playlist/PlayListEdit.tsx
  src/pages/profile/ProfileUpdate.tsx
  src/stores/useAuthStore.ts
Labels: 🐛 Bug, 🛠️ Fix

#167 [fix] 토스트 메세지에 맞는 status를 불러오도록 수정
  src/components/PlaylistCard.tsx
  src/hooks/useDetailForm.ts
  src/hooks/usePlaylistActions.ts
  src/pages/common/Detail.tsx
  src/pages/playlist/PlayListAdd.tsx
  src/pages/playlist/PlayListEdit.tsx
Labels: 🛠️ Fix

#161 [bug] 팔로잉 팔로워 인기 페이지 버그 해결
  src/api/followingPlaylists.ts
  src/hooks/useTagFetch.ts
  src/pages/common/Following.tsx
  src/pages/profile/ProfileFollower.tsx
  src/pages/profile/ProfileFollowing.tsx
Labels: 🐛 Bug

#170 [feature] 사운드클라우드 링크 지원
  src/assets/soundcloud.png
  src/components/Video.tsx
  src/components/playlist/AddedVideo.tsx
  src/constants/validation.ts
  src/pages/common/Detail.tsx
  src/pages/common/SignIn.tsx
  src/pages/playlist/PlayListAdd.tsx
  src/pages/playlist/PlayListEdit.tsx
  src/stores/useAuthStore.ts
  src/utils/videoUtils.ts
Labels: ✨ Feature, 🛠️ Fix

#172 [bug] 로그아웃시 처음 로그인 정보(isFirstLogin) 초기화 되는 문제 해결
  src/stores/useAuthStore.ts
Labels: 🐛 Bug, 🛠️ Fix

#171 [fix]좋아요 버그 해결, 팔로잉 팔로워 리스트 기능 추가
  src/api/followingPlaylists.ts
  src/hooks/useFollowingPlaylist.ts
  src/hooks/useGenerateTags .ts
  src/hooks/usePopularPlaylist.ts
  src/hooks/useTagFetch.ts
  src/pages/common/Following.tsx
  src/pages/common/Popular.tsx
  src/pages/profile/ProfileFollower.tsx
  src/pages/profile/ProfileFollowing.tsx
  src/utils/filterUtils.ts
  src/utils/randomTags.ts
Labels: 🐛 Bug, 🛠️ Fix

#174 [docs] REDAME 작성
  README.md
  src/components/Comment.tsx
  src/components/PlaylistCard.tsx
  src/pages/profile/ProfileHome.tsx
Labels: 📃 Docs, 🛠️ Fix

#179 [refector] 코드 리뷰 수정사항 반영
  src/api/homePlaylists.ts
  src/api/searchPlaylists.ts
  src/components/Button.tsx
  src/hooks/useHomePlaylist.ts
  src/hooks/useSearchPlaylist.ts
  src/pages/common/Home.tsx
  src/pages/common/Search.tsx
Labels: 🪛 Refactor
