Repository Dev-FE-1/Toy_Project_3_Team5, pull requests merged in 2024-08, with the labels that each got.

#18 [feature] 글로벌 스타일 정의 및 프로젝트 세팅 수정
  .eslintrc.cjs
  .husky/pre-commit
  .prettierrc
  .prettierrc.cjs
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/constants/color.ts
  src/constants/font.ts
  src/main.tsx
  src/styles/GlobalStyles.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#26 [fix] 프로젝트 초기 세팅 수정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  tsconfig.app.json
  tsconfig.json
Labels: 🛠️ Fix

#24 [fix] GlobalStyle 수정
  src/constants/colors.ts
  src/styles/GlobalStyles.tsx
Labels: 🛠️ Fix

#27 [feature] 토글 컴포넌트 개발 (#4)
  package-lock.json
  package.json
  src/components/Toggle.tsx
Labels: ✨ Feature

#28 [feature] 토스트 메세지 컴포넌트 개발
  src/components/Toast.tsx
Labels: ✨ Feature

#29 [feature] 개별영상(소) 컴포넌트 개발
  src/assets/defaultThumbnail.jpg
  src/components/Video.tsx
  src/hooks/useVideo.ts
  src/utils/textUtils.ts
Labels: ✨ Feature

#30 [feature] 댓글 컴포넌트 개발
  src/components/Comment.tsx
  src/hooks/useComment.ts
Labels: ✨ Feature

#31 [feature] Button 컴포넌트 구현
  src/assets/google_icon.svg
  src/components/Button.tsx
  src/vite-env.d.ts
Labels: ✨ Feature

#35 [feature] 모달 컴포넌트 개발
  src/components/Modal.tsx
  src/stores/useModalStore.ts
Labels: ✨ Feature

#36 [feature] IconButton 컴포넌트 구현
  src/components/IconButton.tsx
Labels: ✨ Feature

#38 Firebase: firebase 환경 설정 #22
  .gitignore
  src/env.d.ts
  src/firebase/firbaseConfig.ts
  src/hooks/useVideo.ts
Labels: 🔥 Firebase

#39 [feature] HashTag 컴포넌트 구현
  src/components/HashTag.tsx
  src/hooks/useTagSelection.ts
Labels: ✨ Feature

#41 [feature] TextFilter 컴포넌트 구현
  src/components/IconButton.tsx
  src/components/TextFilter.tsx
Labels: ✨ Feature

#42 [feature] Profile 컴포넌트 구현
  src/components/Profile.tsx
Labels: ✨ Feature

#43 [feature] 케밥 버튼 컴포넌트 개발
  src/components/KebabButton.tsx
Labels: ✨ Feature

#45 [feature] PopupFilter 컴포넌트 구현
  src/components/PopupFilter.tsx
Labels: ✨ Feature

#40 [feature] CheckBox 컴포넌트 구현
  src/components/CheckBox.tsx
Labels: ✨ Feature

#37 [feature] 라우팅 로직 구성
  package-lock.json
  package.json
  src/App.tsx
  src/component/Layout.tsx
  src/component/TempFooter.tsx
  src/constants/route.ts
  src/pages/common/Detail.tsx
  src/pages/common/Following.tsx
  src/pages/common/HashTag.tsx
  src/pages/common/Home.tsx
  src/pages/common/NotFound.tsx
  src/pages/common/Popular.tsx
  src/pages/common/Search.tsx
  src/pages/common/SignIn.tsx
  src/pages/common/SignUp.tsx
  src/pages/playlist/PlayList.tsx
  src/pages/playlist/PlayListAdd.tsx
  src/pages/playlist/PlayListHome.tsx
  src/pages/playlist/PlayListLikes.tsx
  src/pages/playlist/PlayListSaved.tsx
  src/pages/playlist/PlayListUpdate.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/ProfileFollower.tsx
  src/pages/profile/ProfileFollowing.tsx
  src/pages/profile/ProfileHome.tsx
  src/pages/profile/ProfileUpdate.tsx
  src/router/router.tsx
Labels: ✨ Feature

#64 [fix] 플레이리스트 카드 컴포넌트 수정
  src/components/PlaylistCard.tsx
  src/components/card/LargePlaylistCard.tsx
  src/components/card/SmallPlaylistCard.tsx
Labels: 🛠️ Fix

#68 [design] Layout 페이지 스타일링
  src/components/Layout.tsx
  src/styles/GlobalStyles.tsx
Labels: 🎨 Design

#71 [fix] Header 컴포넌트 수정
  src/assets/profile_default.png
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/SearchBar.tsx
Labels: 🛠️ Fix

#66 [feature] tab버튼 개발
  src/components/TabButton.tsx
Labels: ✨ Feature

#73 [feature] Navbar 컴포넌트 구현
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/TempFooter.tsx
  src/pages/common/NotFound.tsx
Labels: ✨ Feature

#75 [ design] 마이플리 페이지 퍼블리싱 작업 완료
  src/pages/playlist/PlayList.tsx
  src/pages/playlist/PlayListHome.tsx
  src/pages/playlist/PlayListLikes.tsx
  src/pages/playlist/PlayListSaved.tsx
Labels: 🎨 Design

#76 [fix] 케밥버튼, 플레이리스트 카드, NavBar 컴포넌트 스타일 수정
  src/components/KebabButton.tsx
  src/components/Navbar.tsx
  src/components/PlaylistCard.tsx
Labels: 🛠️ Fix

#84 [fix] Button 컴포넌트 수정
  src/components/Button.tsx
Labels: 🛠️ Fix

#85 [design] 마이페이지 UI 퍼블리싱
  src/pages/profile/ProfileHome.tsx
Labels: 🎨 Design

#77 [feature] 인기 페이지 개발
  src/components/Button.tsx
  src/mock/popularPlaylist-test.ts
  src/pages/common/Popular.tsx
Labels: ✨ Feature

#86 [design] 404 페이지 퍼블리싱 작업
  src/assets/404.png
  src/pages/common/NotFound.tsx
Labels: 🎨 Design
